CREATE TABLE IF NOT EXISTS requests (
  id SERIAL PRIMARY KEY,
  asset TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);